### ISSUE TITLE
Uses a lot of memory

### ISSUE THREAD

**Issue by diwu1989** [kevva/download#53]
If I download a really large file, it eats up a lot of memory. Is there any way to have it stream the output to the destination?

Try downloading a 1GB file

**Comment by shinnn** [comment]
@diwu1989 Which extension of the file do you want to download? Maybe the other module helps you instead of this.

**Comment by kevva** [comment]
If you only need to download a file you might be better of using https://github.com/sindresorhus/got/.

**Comment by timlesallen** [comment]
@kevva I also got bitten by this.  I assumed this module would do things 'the right way' with the `download(uri, dest)` invocation and stream to the file in `dest`, but instead it puts the whole file in memory first...  For large files I don't think this is what the developer intends/expects.  I'll have to refactor my code now to use `got` instead.  Just mentioning this as I think it's not ideal.  Maybe make it clear in the README and/or consider a refactor to stream _where possible_?  Thanks for your hard work!

**Comment by kevva** [comment]
@timlesallen, you could use the streaming API showcased in the [docs](https://github.com/kevva/download#usage).

**Comment by timlesallen** [comment]
@kevva: Thanks for the comment.  I did see the streaming options, but then we're missing out some of the functionality I was wanting from `download`, which is to write to the destination I specify.

My point is not that it can't do streams  (if you are happy to manage the 'writable side of the stream') - my point is that is _should_ stream under the hood/internally when downloading to a destination in the `download(uri, dest)` case because using all the memory the download file takes up is needlessly inefficient and probably not what the developer expects.  

What do you think?
